# -*- coding: utf-8 -*-
"""Tarea6_Perfil_Despacho_Oficial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13woHErr1wdISLSrA9ZX_Z8bDaxDXKScT
"""

import pandas as pd

df = pd.read_csv("precios_energia.csv", header=None, names=["timestamp", "precio_usd_mwh"])

df["timestamp"] = pd.to_datetime(df["timestamp"], format="%m/%d/%y %I:%M %p")

#enero y junio

df = df[df["timestamp"].dt.month.isin([1, 6])].copy()
df = df.sort_values("timestamp").reset_index(drop=True)

# Crear columnas útiles
df["fecha"] = df["timestamp"].dt.date
df["hora"] = df["timestamp"].dt.hour

print("Horas enero + junio:", len(df))

# =========================
# encontramos los dos bloques de carga por día
# =========================

P_carga_MW = 100
duracion_bloque_h = 3
n_bloques_carga = 2

# Inicializar perfil de despacho
df["P_cmd_MW"] = 0.0
df["tipo_operacion"] = "reposo"

bloques_carga = []

# =========================
# 3. Buscar bloques por día
# =========================

for fecha, grupo in df.groupby("fecha"):
    grupo = grupo.sort_values("timestamp").copy()

    candidatos = []

    # Revisar todos los bloques consecutivos posibles dentro del día
    for i in range(0, len(grupo) - duracion_bloque_h + 1):
        bloque = grupo.iloc[i:i + duracion_bloque_h]

        # Verificar que el bloque sea realmente continuo
        duracion_real = (
            bloque["timestamp"].iloc[-1] - bloque["timestamp"].iloc[0]
        ).total_seconds() / 3600

        if duracion_real == duracion_bloque_h - 1:
            precio_promedio = bloque["precio_usd_mwh"].mean()
            costo_total = bloque["precio_usd_mwh"].sum() * P_carga_MW

            candidatos.append({
                "fecha": fecha,
                "indices": bloque.index.tolist(),
                "inicio": bloque["timestamp"].iloc[0],
                "fin": bloque["timestamp"].iloc[-1],
                "precio_promedio_usd_mwh": precio_promedio,
                "costo_total_usd": costo_total
            })

    # Ordenar bloques desde el más barato
    candidatos = sorted(candidatos, key=lambda x: x["precio_promedio_usd_mwh"])

    bloques_elegidos = []
    indices_ocupados = set()

    # Elegir 2 bloques sin traslape
    for candidato in candidatos:
        indices_bloque = set(candidato["indices"])

        if indices_ocupados.isdisjoint(indices_bloque):
            bloques_elegidos.append(candidato)
            indices_ocupados.update(indices_bloque)

        if len(bloques_elegidos) == n_bloques_carga:
            break

    # Guardar bloques seleccionados
    for bloque in bloques_elegidos:
        df.loc[bloque["indices"], "P_cmd_MW"] = -P_carga_MW
        df.loc[bloque["indices"], "tipo_operacion"] = "carga"
        bloques_carga.append(bloque)

# Convertir resumen a DataFrame
df_bloques_carga = pd.DataFrame(bloques_carga)

print(df_bloques_carga.head())

df.info()

df_bloques_carga.info()

"""por lo tanto, en **df** tenemos todas las horas de enero y junio combinadas, teniendo un total de 61 x 24 = 1464 horas. en **df_bloques_carga** tendremos los bloques de carga que son 2 horas de carga por día. donde 2 x 61 es 122.

Guardamos el perfil:
"""

df.to_csv("perfil_despacho_carga_2_bloques_diarios.csv", index=False)
df_bloques_carga.to_csv("resumen_bloques_carga.csv", index=False)

#print(df[df["tipo_operacion"] == "carga"].head(20))

"""Ahora vamos por los bloques de descarga"""

# =========================
# Parámetros de descarga
# =========================

P_descarga_MW = 74
duracion_bloque_h = 1
n_bloques_descarga = 2

bloques_descarga = []

# =========================
# Buscar bloques de descarga por día
# =========================

for fecha, grupo in df.groupby("fecha"):
    grupo = grupo.sort_values("timestamp").copy()

    candidatos = []

    # Revisar todos los bloques consecutivos posibles dentro del día
    for i in range(0, len(grupo) - duracion_bloque_h + 1):
        bloque = grupo.iloc[i:i + duracion_bloque_h]

        # Verificar que el bloque sea realmente continuo
        duracion_real = (
            bloque["timestamp"].iloc[-1] - bloque["timestamp"].iloc[0]
        ).total_seconds() / 3600

        if duracion_real == duracion_bloque_h - 1:

            # Evitar que el bloque se traslape con horas de carga
            if (bloque["tipo_operacion"] == "carga").any():
                continue

            precio_promedio = bloque["precio_usd_mwh"].mean()
            ingreso_total = bloque["precio_usd_mwh"].sum() * P_descarga_MW

            candidatos.append({
                "fecha": fecha,
                "indices": bloque.index.tolist(),
                "inicio": bloque["timestamp"].iloc[0],
                "fin": bloque["timestamp"].iloc[-1],
                "precio_promedio_usd_mwh": precio_promedio,
                "ingreso_total_usd": ingreso_total
            })

    # Ordenar bloques desde el más caro
    candidatos = sorted(
        candidatos,
        key=lambda x: x["precio_promedio_usd_mwh"],
        reverse=True
    )

    bloques_elegidos = []
    indices_ocupados = set()

    # Elegir 2 bloques sin traslape entre ellos
    for candidato in candidatos:
        indices_bloque = set(candidato["indices"])

        if indices_ocupados.isdisjoint(indices_bloque):
            bloques_elegidos.append(candidato)
            indices_ocupados.update(indices_bloque)

        if len(bloques_elegidos) == n_bloques_descarga:
            break

    # Guardar bloques seleccionados en el DataFrame principal
    for bloque in bloques_elegidos:
        df.loc[bloque["indices"], "P_cmd_MW"] = P_descarga_MW
        df.loc[bloque["indices"], "tipo_operacion"] = "descarga"
        bloques_descarga.append(bloque)

# Convertir resumen a DataFrame
df_bloques_descarga = pd.DataFrame(bloques_descarga)

print(df_bloques_descarga.head())

df_bloques_descarga.info()

"""Guardamos el perfil"""

df.to_csv("perfil_despacho_completo_preliminar.csv", index=False)
df_bloques_descarga.to_csv("resumen_bloques_descarga.csv", index=False)

"""# Resumimos #"""

# =========================
# Balance económico preliminar
# =========================

dt_h = 1  # paso horario

# Energía comprada en carga
df["E_comprada_MWh"] = df["P_cmd_MW"].where(
    df["P_cmd_MW"] < 0, 0
).abs() * dt_h

# Energía vendida en descarga
df["E_vendida_MWh"] = df["P_cmd_MW"].where(
    df["P_cmd_MW"] > 0, 0
) * dt_h

# Costo de comprar energía para cargar
df["costo_carga_USD"] = (
    df["E_comprada_MWh"] * df["precio_usd_mwh"]
)

# Ingreso por vender energía en descarga
df["ingreso_descarga_USD"] = (
    df["E_vendida_MWh"] * df["precio_usd_mwh"]
)

# Margen bruto horario
df["flujo_bruto_USD"] = (
    df["ingreso_descarga_USD"] - df["costo_carga_USD"]
)

# =========================
# Resumen para enero + junio
# =========================

resumen_61d = {
    "horas_totales": len(df),
    "dias_simulados": df["fecha"].nunique(),
    "horas_carga": (df["tipo_operacion"] == "carga").sum(),
    "horas_descarga": (df["tipo_operacion"] == "descarga").sum(),
    "E_comprada_MWh": df["E_comprada_MWh"].sum(),
    "E_vendida_MWh": df["E_vendida_MWh"].sum(),
    "precio_promedio_carga_USD_MWh": df.loc[
        df["E_comprada_MWh"] > 0, "precio_usd_mwh"
    ].mean(),
    "precio_promedio_descarga_USD_MWh": df.loc[
        df["E_vendida_MWh"] > 0, "precio_usd_mwh"
    ].mean(),
    "costo_carga_USD": df["costo_carga_USD"].sum(),
    "ingreso_descarga_USD": df["ingreso_descarga_USD"].sum(),
    "margen_bruto_USD": df["flujo_bruto_USD"].sum()
}

resumen_61d = pd.DataFrame([resumen_61d])
pd.set_option("display.float_format", "{:.2f}".format)

print(resumen_61d.T)